root = "."

tmp_dir = ".tmp"

[build]
  cmd = "go build -o ./.tmp/api ./cmd/api"
  bin = ".tmp/api"
  include_ext = ["go"]
  exclude_dir = [".git", ".tmp", "vendor"]
  delay = 200

[log]
  time = true

[misc]
  clean_on_exit = true
